[phases.setup]
nixPkgs = ["python3", "nodejs", "git", "gcc", "openssl", "libatomic", "libgcc"]

[phases.build]
cmds = ["pip install -r requirements.txt", "python -m prisma generate"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8000}"
